package com.jinrong.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@TableName("cash_flow_statement")
public class CashFlowStatement {
    @TableId(value = "id")
    private String id;
    private String tsCode;
    private LocalDate annDate;
    private LocalDate fAnnDate;
    private LocalDate endDate;
    private String compType;
    private String reportType;
    private String endType;
    private BigDecimal netProfit;
    private BigDecimal finanExp;
    private BigDecimal cFrSaleSg;
    private BigDecimal recpTaxRends;
    private BigDecimal nDeposIncrFi;
    private BigDecimal nIncrLoansCb;
    private BigDecimal nIncBorrOthFi;
    private BigDecimal premFrOrigContr;
    private BigDecimal nIncrInsuredDep;
    private BigDecimal nReinsurPrem;
    private BigDecimal nIncrDispTfa;
    private BigDecimal ifcCashIncr;
    private BigDecimal nIncrDispFaas;
    private BigDecimal nIncrLoansOthBank;
    private BigDecimal nCapIncrRepur;
    private BigDecimal cFrOthOperateA;
    private BigDecimal cInfFrOperateA;
    private BigDecimal cPaidGoodsS;
    private BigDecimal cPaidToForEmpl;
    private BigDecimal cPaidForTaxes;
    private BigDecimal nIncrCltLoanAdv;
    private BigDecimal nIncrDepCbob;
    private BigDecimal cPayClaimsOrigInco;
    private BigDecimal payHandlingChrg;
    private BigDecimal payCommInsurPlcy;
    private BigDecimal othCashPayOperAct;
    private BigDecimal stCashOutAct;
    private BigDecimal nCashflowAct;
    private BigDecimal othRecpRalInvAct;
    private BigDecimal cDispWithdrwlInvest;
    private BigDecimal cRecpReturnInvest;
    private BigDecimal nRecpDispFiolta;
    private BigDecimal nRecpDispSobu;
    private BigDecimal stotInflowsInvAct;
    private BigDecimal cPayAcqConstFiolta;
    private BigDecimal cPaidInvest;
    private BigDecimal nDispSubsOthBiz;
    private BigDecimal othPayRalInvAct;
    private BigDecimal nIncrPledgeLoan;
    private BigDecimal stotOutInvAct;
    private BigDecimal nCashflowInvAct;
    private BigDecimal cRecpBorrow;
    private BigDecimal procIssueBonds;
    private BigDecimal othCashRecpRalFncAct;
    private BigDecimal stotCashInFncAct;
    private BigDecimal freeCashflow;
    private BigDecimal cPrepayAmtBorr;
    private BigDecimal cPayDistDpcpIntExp;
    private BigDecimal inclDvdProfitPaidScMs;
    private BigDecimal othCashpayRalFncAct;
    private BigDecimal stotCashoutFncAct;
    private BigDecimal nCashFlowsFncAct;
    private BigDecimal effFxFluCash;
    private BigDecimal nIncrCashCashEqu;
    private BigDecimal cCashEquBegPeriod;
    private BigDecimal cCashEquEndPeriod;
    private BigDecimal cRecpCapContrib;
    private BigDecimal inclCashRecSaims;
    private BigDecimal unconInvestLoss;
    private BigDecimal provDeprAssets;
    private BigDecimal deprFaCogaDpba;
    private BigDecimal amortIntangAssets;
    private BigDecimal ltAmortDeferredExp;
    private BigDecimal decrDeferredExp;
    private BigDecimal incrAccExp;
    private BigDecimal lossDispFiolta;
    private BigDecimal lossScrFa;
    private BigDecimal lossFvChg;
    private BigDecimal investLoss;
    private BigDecimal decrDefIncTaxAssets;
    private BigDecimal incrDefIncTaxLiab;
    private BigDecimal decrInventories;
    private BigDecimal decrOperPayable;
    private BigDecimal incrOperPayable;
    private BigDecimal others;
    private BigDecimal imNetCashflowOperAct;
    private BigDecimal convDebtIntoCap;
    private BigDecimal convCopbondsDueWithin1y;
    private BigDecimal faFncLeases;
    private BigDecimal imNIncrCashEqu;
    private BigDecimal netDismCapitalAdd;
    private BigDecimal netCashReceSec;
    private BigDecimal creditImpaLoss;
    private BigDecimal useRightAssetDep;
    private BigDecimal othLossAsset;
    private BigDecimal endBalCash;
    private BigDecimal begBalCash;
    private BigDecimal endBalCashEqu;
    private BigDecimal begBalCashEqu;
    private String updateFlag;
}