package com.jinrong.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@TableName("income_statement")
public class IncomeStatement {
    @TableId(value = "id" )
    private String id;
    private String tsCode;
    private LocalDate annDate;
    private LocalDate fAnnDate;
    private LocalDate endDate;
    private String reportType;
    private String compType;
    private String endType;
    private BigDecimal basicEps;
    private BigDecimal dilutedEps;
    private BigDecimal totalRevenue;
    private BigDecimal revenue;
    private BigDecimal intIncome;
    private BigDecimal premEarned;
    private BigDecimal commIncome;
    private BigDecimal nCommisIncome;
    private BigDecimal nOthIncome;
    private BigDecimal nOthBIncome;
    private BigDecimal premIncome;
    private BigDecimal outPrem;
    private BigDecimal unePremReser;
    private BigDecimal reinsIncome;
    private BigDecimal nSecTbIncome;
    private BigDecimal nSecUwIncome;
    private BigDecimal nAssetMgIncome;
    private BigDecimal othBIncome;
    private BigDecimal fvValueChgGain;
    private BigDecimal investIncome;
    private BigDecimal assInvestIncome;
    private BigDecimal forexGain;
    private BigDecimal totalCogs;
    private BigDecimal operCost;
    private BigDecimal intExp;
    private BigDecimal commExp;
    private BigDecimal bizTaxSurchg;
    private BigDecimal sellExp;
    private BigDecimal adminExp;
    private BigDecimal finExp;
    private BigDecimal assetsImpairLoss;
    private BigDecimal premRefund;
    private BigDecimal compensPayout;
    private BigDecimal reserInsurLiab;
    private BigDecimal divPayt;
    private BigDecimal reinsExp;
    private BigDecimal operExp;
    private BigDecimal compensPayoutRefu;
    private BigDecimal insurReserRefu;
    private BigDecimal reinsCostRefund;
    private BigDecimal otherBusCost;
    private BigDecimal operateProfit;
    private BigDecimal nonOperIncome;
    private BigDecimal nonOperExp;
    private BigDecimal ncaDisploss;
    private BigDecimal totalProfit;
    private BigDecimal incomeTax;
    private BigDecimal nIncome;
    private BigDecimal nIncomeAttrP;
    private BigDecimal minorityGain;
    private BigDecimal othComprIncome;
    private BigDecimal tComprIncome;
    private BigDecimal comprIncAttrP;
    private BigDecimal comprIncAttrMS;
    private BigDecimal ebit;
    private BigDecimal ebitda;
    private BigDecimal insuranceExp;
    private BigDecimal undistProfit;
    private BigDecimal distableProfit;
    private BigDecimal rdExp;
    private BigDecimal finExpIntExp;
    private BigDecimal finExpIntInc;
    private BigDecimal transferSurplusRese;
    private BigDecimal transferHousingImprest;
    private BigDecimal transferOth;
    private BigDecimal adjLossgain;
    private BigDecimal withdraLegalSurplus;
    private BigDecimal withdraLegalPubfund;
    private BigDecimal withdraBizDevfund;
    private BigDecimal withdraReseFund;
    private BigDecimal withdraOthErsu;
    private BigDecimal workersWelfare;
    private BigDecimal distrProfitShrhder;
    private BigDecimal prfsharePayableDvd;
    private BigDecimal comsharePayableDvd;
    private BigDecimal capitComstockDiv;
    private BigDecimal netAfterNrLpCorrect;
    private BigDecimal creditImpaLoss;
    private BigDecimal netExpoHedgingBenefits;
    private BigDecimal othImpairLossAssets;
    private BigDecimal totalOpcost;
    private BigDecimal amodcostFinAssets;
    private BigDecimal othIncome;
    private BigDecimal assetDispIncome;
    private BigDecimal continuedNetProfit;
    private BigDecimal endNetProfit;
    private String updateFlag;
}